#pragma once
#include "pros/adi.hpp"
#include "EZ-Template/api.hpp"
#include "globals.hpp"
#include "autons.hpp"
#include "main.h"
#include "driverControl.hpp"
void default_constants();

void drive_example();
void turn_example();
void drive_and_turn();
void wait_until_change_speed();
void swing_example();
void motion_chaining();
void combining_movements();
void interfered_example();
void odom_drive_example();
void odom_pure_pursuit_example();
void odom_pure_pursuit_wait_until_example();
void odom_boomerang_example();
void odom_boomerang_injected_pure_pursuit_example();
void measure_offsets();